export const chamadoData = {
  id: "001234",
  titulo: "Portão da garagem com defeito",
  descricao:
    "O portão não abre completamente e faz ruído estranho ao tentar fechar. Problema começou ontem após chuva forte.",
  status: "em_andamento",
  prioridade: "alta",
  categoria: "Manutenção Predial",
  equipamento: "Portão Automático - Garagem Principal",
  dataCriacao: "2024-01-20T10:30:00",
  dataAtualizacao: "2024-01-20T14:15:00",
  tempoDecorrido: "3h 45min",
  slaRestante: "4h 15min",
  solicitante: {
    nome: "João Silva",
    email: "joao.silva@empresa.com",
    telefone: "(11) 99999-9999",
    localizacao: "Bloco A - Apartamento 205",
    avatar: "/professional-man.png",
  },
  tecnico: {
    nome: "Carlos Mendes",
    email: "carlos.mendes@calltech.com",
    telefone: "(11) 88888-8888",
    especialidade: "Sistemas Elétricos",
    avatar: "/technician-man.png",
  },
  historico: [
    {
      id: 1,
      tipo: "criacao",
      descricao: "Chamado criado",
      usuario: "João Silva",
      data: "2024-01-20T10:30:00",
    },
    {
      id: 2,
      tipo: "atribuicao",
      descricao: "Chamado atribuído para Carlos Mendes",
      usuario: "Sistema",
      data: "2024-01-20T11:00:00",
    },
    {
      id: 3,
      tipo: "comentario",
      descricao: "Técnico a caminho do local. Previsão de chegada: 30 minutos.",
      usuario: "Carlos Mendes",
      data: "2024-01-20T14:15:00",
    },
  ],
  anexos: [
    { nome: "foto_portao.jpg", tipo: "imagem", tamanho: "2.3 MB" },
    { nome: "manual_equipamento.pdf", tipo: "documento", tamanho: "1.8 MB" },
  ],
}
